language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  nosetests -v
notifications:
  email:
    recipients:
      - ankursinha@fedoraproject.org
    on_success: never
    on_failure: always
